# Generated by Django 4.1.4 on 2022-12-10 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=200)),
                ('product_description', models.TextField(max_length=200)),
                ('strain', models.TextField(max_length=200)),
                ('place_of_dispatch', models.CharField(choices=[('kiina', 'kiina'), ('jenkit', 'jenkit')], max_length=200)),
                ('accepted_delivery_destinations', models.CharField(choices=[('kiina', 'kiina'), ('jenkit', 'jenkit')], max_length=200)),
                ('delivery_option', models.CharField(choices=[('kiina', 'kiina'), ('jenkit', 'jenkit')], max_length=200)),
                ('pricing_currency', models.CharField(choices=[('EUR', 'EUR'), ('USD', 'USD')], max_length=200)),
                ('pricing_unit', models.CharField(choices=[('gram', 'gram'), ('ounce', 'ounce')], default='gram', max_length=200)),
                ('pricing_type_simple', models.BooleanField(default=True)),
                ('pricing_type_advanced', models.BooleanField(default=False)),
                ('simple_price', models.IntegerField()),
                ('advanced_price', models.IntegerField()),
            ],
        ),
    ]
