# Generated by Django 5.2.5 on 2025-09-05 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityModel',
            fields=[
                ('custom_id', models.AutoField(primary_key=True, serialize=False)),
                ('communityurl', models.CharField()),
                ('url', models.CharField()),
                ('active_users', models.IntegerField()),
                ('created', models.DateTimeField()),
                ('description', models.CharField()),
                ('name', models.CharField()),
                ('token', models.CharField()),
            ],
        ),
    ]
