# Generated by Django 5.2.5 on 2025-09-05 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitymodel',
            name='user',
            field=models.CharField(default='asd'),
        ),
    ]
