# Generated by Django 4.1.4 on 2023-03-11 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='slug',
            field=models.SlugField(default='', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='delivery_option',
            field=models.CharField(max_length=200),
        ),
    ]
