# Generated by Django 5.2.5 on 2025-08-19 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_productmodel_slug_alter_productmodel_delivery_option'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('communityurl', models.CharField()),
                ('url', models.CharField()),
                ('active_users', models.IntegerField()),
                ('created', models.DateTimeField()),
                ('description', models.CharField()),
                ('name', models.CharField()),
                ('token', models.CharField()),
                ('slug', models.SlugField()),
            ],
        ),
    ]
