# Generated by Django 5.2.5 on 2025-08-19 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_communitymodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communitymodel',
            name='id',
        ),
        migrations.AddField(
            model_name='communitymodel',
            name='custom_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
