# Generated by Django 5.2.5 on 2025-08-24 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_communitymodel_id_communitymodel_custom_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communitymodel',
            name='slug',
        ),
    ]
